name: Kyle Schmidt
description: Thoughts, notes, and rants of a web developer in Eugene
gravatar_url: http://www.gravatar.com/avatar/645ec044741c8ea02114bd215f18e0e6.png
twitter: kyle_r_schmidt
github: krschmidt
linkedin: krschmidt
goodreads: VeryHungryRaptor
url: http://kyleschmidt.com
google_analytics: UA-3315743-1

gems:
 - jekyll-sitemap