name: Kyle Schmidt
description: Thoughts, notes, and rants of a web developer in Eugene
gravatar_url: https://www.gravatar.com/avatar/645ec044741c8ea02114bd215f18e0e6.png
github: krschmidt
linkedin: krschmidt
goodreads: VeryHungryRaptor
url: https://kyleschmidt.com
google_analytics: UA-3315743-1

plugins:
 - jekyll-sitemap